06:29:47 PM:DEBUG [logger_base.py:18] Mensaje a nivel debug
06:29:47 PM:INFO [logger_base.py:19] Mensaje a nivel info
06:29:47 PM:WARNING [logger_base.py:20] Mensaje a nivel warning
06:29:47 PM:ERROR [logger_base.py:21] Mensaje a nivel error
06:29:47 PM:CRITICAL [logger_base.py:22] Mensaje a nivel critical
04:22:49 PM:DEBUG [Persona.py:51] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@gmail.com
        
04:26:58 PM:DEBUG [Persona.py:51] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@gmail.com
        
04:28:37 PM:DEBUG [Persona.py:51] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@gmail.com
        
04:30:45 PM:DEBUG [Persona.py:51] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@gmail.com
        
04:30:45 PM:DEBUG [Persona.py:53] 
            Id Persona: Mari,
            Nombre: Salgado,
            Apellido: marisal@gmail.com,
            Email: None
        
04:31:47 PM:DEBUG [Persona.py:51] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@gmail.com
        
04:31:47 PM:DEBUG [Persona.py:53] 
            Id Persona: None,
            Nombre: Mari,
            Apellido: Salgado,
            Email: marisal@gmail.com
        
04:46:43 PM:DEBUG [Persona.py:51] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@gmail.com
        
04:46:43 PM:DEBUG [Persona.py:53] 
            Id Persona: None,
            Nombre: Mari,
            Apellido: Salgado,
            Email: marisal@gmail.com
        
04:46:43 PM:DEBUG [Persona.py:55] 
            Id Persona: 1,
            Nombre: None,
            Apellido: None,
            Email: None
        
05:58:10 PM:DEBUG [conexion.py:23] Conexión Exitosa: <connection object at 0x00000199261F1F10; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
06:00:56 PM:DEBUG [conexion.py:23] Conexión Exitosa: <connection object at 0x00000198C3FE9F10; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
06:00:56 PM:ERROR [conexion.py:39] Ocurrió un error: 'NoneType' object has no attribute 'cursor'
06:03:09 PM:DEBUG [conexion.py:23] Conexión Exitosa: <connection object at 0x000001C0DCDE9F10; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
06:03:09 PM:ERROR [conexion.py:39] Ocurrió un error: 'NoneType' object has no attribute 'cursor'
06:03:34 PM:DEBUG [conexion.py:23] Conexión Exitosa: <connection object at 0x0000013B8BED9F10; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
06:03:34 PM:DEBUG [conexion.py:36] Se abrió correctamente el cursor: <cursor object at 0x0000013B8BE74820; closed: 0>
